package com.pomplatform.client.workflow.personnelbusiness.form;

import java.util.Date;

import com.delicacy.client.data.KeyValueManager;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.smartgwt.client.data.Record;
import com.smartgwt.client.widgets.Label;
import com.smartgwt.client.widgets.layout.VLayout;

public class ApplyForTransferPrintView extends VLayout {

	public ApplyForTransferPrintView(Record record) {
		Label a = new Label("");
		String htmlStr = "<style>" 
				+ " 		*{" 
				+ "		font-family:'微软雅黑';" 
				+ "} " 
				+ "		th{"
				+ "			font-weight:normal;" 
				+ "		}" 
				+ "		td{" 
				+ "			text-align:center;"
				+ "		}" 
				+ "	</style>" 
				+ "    <div style='width: 750px;'>" 
				+ "		<!--表格1内容star--> "
				+ "		<center style='height:1090px;position: relative;'>" 
				+ "			<!--表头star-->"
				+ "<!-- 			<div style='height:43px; border-bottom: 1px solid #000;'>"
				+ "	<img src = 'logo.png' style='float:left; height:40px;'/>"
				+ "	<font style='text-align:right;width:750px;position: absolute; top: 20px; left:0px;font-size:14px;color:#e3e3e3;margin-right:10px;'>版/修(4/0)　　文件编号：J&A/QR62F-ARH　</font>"
				+ "</div> -->" 
				+ "			<!--表头over-->"
				+ "				<table border='1' cellpadding='0' cellspacing='0' style ='margin-top:0px;'>"
				+ "							<caption style='font-size: 22px;font-weight: bold;'>"
				+ "							   员工调动申请单"
				+ "							   <p style='font-size:14px;text-align:right;margin: 5px 0;'>填表日期：<span type='text' style='border-bottom:1px solid #333;'>createTime</span></p>"
				+ "							</caption>	" 
				+ ""
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='125' height='40'>原工号</td>"
				+ "								<td width='250' height='40'>employeeNo</td>"
				+ "								<td width='125' height='40'>姓名</td>"
				+ "								<td width='250' height='40'>employeeName</td>"
				+ "								<td width='125' height='40'>原部门</td>"
				+ "								<td width='250' height='40'>departmentName</td>"
				+ "							</tr>" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td widtd='125' height='40'>调入部门</td>"
				+ "								<td width='250' height='40' colspan='2'>toDepartmentName</td>"
				+ "								<td width='125' height='40'>新工号</td>"
				+ "								<td width='250' height='40' colspan='2'></td>"
				+ "							</tr>	" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td widtd='125' height='40'>拟调动时间</td>"
				+ "								<td width='250' height='40' colspan='2'>startDate</td>"
				+ "								<td width='125' height='40'>调动原因</td>"
				+ "								<td width='250' height='40' colspan='2'></td>"
				+ "							</tr>"
				+ "				</table>" 
				+ "				<!--一、工作移交（含待办事项）star-->"
				+ "				<table border='1' cellpadding='0' cellspacing='0' style ='margin-top:-2px;'>"
				+ "							<tr>"
				+ "								<th colspan='3' height='40' style='font-weight:700;font-size:19px;'>一、工 作 移 交（含待办事项）</th>"
				+ "							</tr>				"
				+ "							<tr style='font-size:15px;font-weight:700;'>"
				+ "								<th width='150' height='40' style='font-weight:700'>名称</th>"
				+ "								<th width='300' height='40' style='font-weight:700'>起讫时间</th>"
				+ "								<th width='300' height='40' style='font-weight:700'>接手人</th>"
				+ "							</tr>		" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "							</tr>		" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "							</tr>		" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "							</tr>		" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "							</tr>		" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "							</tr>	" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "								<td width='300' height='40'></td>"
				+ "							</tr>																																																				"
				+ "				</table>" + "				<!--一、工作移交（含待办事项）over-->	"
				+ "				<!--二、公司系统账号关闭star-->"
				+ "				<table border='1' cellpadding='0' cellspacing='0' style ='margin-top:-2px;'>"
				+ "							<tr>"
				+ "								<th colspan='4' height='40' style='font-weight:700;font-size:19px;'>二、资料及办公用具移交</th>"
				+ "							</tr>				"
				+ "							<tr style='font-size:15px;font-weight:700;'>"
				+ "								<th width='150' height='40' style='font-weight:700'>名称</th>"
				+ "								<th width='100' height='40' style='font-weight:700'>数量</th>"
				+ "								<th width='250' height='40' style='font-weight:700'>内容</th>"
				+ "								<th width='250' height='40' style='font-weight:700'>接手人</th>"
				+ "							</tr>		" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='100' ></td>"
				+ "								<td width='250' height='40'></td>"
				+ "								<td width='250' height='40'></td>" 
				+ "							</tr>"
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='100' height='40'></td>"
				+ "								<td width='250' height='40'></td>"
				+ "								<td width='250' height='40'></td>" 
				+ "							</tr>"
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='100' height='40'></td>"
				+ "								<td width='250' height='40'></td>"
				+ "								<td width='250' height='40'></td>"
				+ "							</tr>	" + "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40'></td>"
				+ "								<td width='100' height='40'></td>"
				+ "								<td width='250' height='40'></td>"
				+ "								<td width='250' height='40'></td>"
				+ "							</tr>																																																																															"
				+ "				</table>" + "				<!--二、公司系统账号关闭over-->		"
				+ "				<!--三、资料及办公用具移交star-->"
				+ "				<table border='1' cellpadding='0' cellspacing='0' style ='margin-top:-2px;'>"
				+ "							<tr>"
				+ "								<th colspan='5' height='40' style='font-weight:700;font-size:19px;'>三、其他</th>"
				+ "							</tr>						"
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40' >转出部门意见</td>"
				+ "								<td width='600' height='40' colspan='4' style='position:relative;font-size: 13px;text-align:left;padding:0 3px;'><span style='position:absolute;bottom:5px;right:100px;font-size:12px;'>（签字及日期）</span></td>"
				+ "							</tr>" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='80' >转出部门助理确认</td>"
				+ "								<td width='600' height='80' colspan='4' style='text-align:left;padding:0 3px;position:relative;margin:3px 0; font-size: 13px;'>"
				+ "									转出日期：</br>"
				+ "									当月考勤情况：5分钟内迟到（    ）次、半小时迟到（   ）次、其他时间迟到（    ）次；  事假（      ）天、病假（    ）天；</br>"
				+ "									<span style='position:absolute;bottom:5px;right:85px;font-size:12px;'>（签字及日期）</span>"
				+ "								</td>" 
				+ "							</tr>	"
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40' >转入部门意见</td>"
				+ "								<td width='600' height='40' colspan='4' style='position:relative;font-size: 13px;text-align:left;padding:0 3px;'><span style='position:absolute;bottom:5px;right:100px;font-size:12px;'>（签字及日期）</span></td>"
				+ "							</tr>" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40' >转入部门助理确认</td>"
				+ "								<td width='600' height='40' colspan='4' style='position:relative;text-align:left;padding:0 3px;font-size: 13px;'>"
				+ "									</br>"
				+ "									<span style='position:absolute;bottom:5px;right:100px;font-size:12px;'>（签字及日期）</span></td>"
				+ "							</tr>" 
				+ "							<tr style='font-size:15px;'>"
				+ "								<td width='150' height='40' >人资部审批</td>"
				+ "								<td width='600' height='40' colspan='4' style='position:relative;font-size: 13px;text-align:left;padding:0 3px;'><span style='position:absolute;bottom:5px;right:100px;font-size:12px;'>（签字及日期）</span></td>"
				+ "							</tr>																																																															"
				+ "				</table>"
				+ "				<p style='font-size:14px;text-align:left;margin-top:8px;padding-left:15px;'>说明：转出及转入部门需部门经理、总监/总经理审批。</p>"
				+ "				<!--三、资料及办公用具移交over-->							" 
				+ "			<!--表尾star-->"
				+ "			<!-- <div style='position:absolute; bottom:0px; left:0px;width:750px; height:15px; font-size:12px;color:#e3e3e3;'>　　　　　　　保密等级：机密　　　　　　　　　　　　存档期限：5年　　　　　　　　　　　　第 1 页 共 1 页</div> -->"
				+ "			<!--表尾over-->	" 
				+ "		</center>" + "		<!--表格1内容over--> " 
				+ "    </div>";
		String employeeName = KeyValueManager.getValue("employees", record.getAttributeAsString("employeeId"));
		String oriDepartmentName = KeyValueManager.getValue("departments", record.getAttributeAsString("departmentId"));
		String toDepartmentName = KeyValueManager.getValue("departments", record.getAttributeAsString("parentId"));
		DateTimeFormat __DF = DateTimeFormat.getFormat("yyyy年MM月dd");
		DateTimeFormat __DF1 = DateTimeFormat.getFormat("yyyy.MM.dd");
		htmlStr = htmlStr.replace("employeeNo", record.getAttributeAsString("employeeNo"))
			.replace("employeeName", employeeName)
			.replace("departmentName", oriDepartmentName)
			.replace("toDepartmentName", toDepartmentName)
			.replace("createTime", __DF.format(new Date()))
			.replace("startDate", __DF1.format(record.getAttributeAsDate("startDate")));
		a.setContents(htmlStr);
		addMember(a);
	}
}
